/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dhea.view;

import java.awt.event.KeyEvent;
import javax.swing.JTable;
import javax.swing.JTextField;
import dhea.controller.PengembalianController;

/**
 *
 * @author hp
 */
public class FormPengembalian extends javax.swing.JFrame {

    /**
     * Creates new form FormPengembalian
     */
    PengembalianController controller;
    public FormPengembalian() {
        initComponents();
        controller = new PengembalianController(this);
        controller.clear();
        controller.viewTable(); 
    }

    public JTable getTabelPengembalian() {
        return TabelPengembalian;
    }

    public JTextField getTxtTerlambat() {
        return txtTerlambat;
    }

    public JTextField getTxtDenda() {
        return txtDenda;
    }

    public JTextField getTxtJudulbuku() {
        return txtJudulbuku;
    }

    public JTextField getTxtKodeanggota() {
        return txtKodeanggota;
    }

    public JTextField getTxtKodebuku() {
        return txtKodebuku;
    }

    public JTextField getTxtNamaanggota() {
        return txtNamaanggota;
    }

    public JTextField getTxtTanggalDikembalikan() {
        return txtTanggalDikembalikan;
    }

    public JTextField getTxtTanggalkembali() {
        return txtTanggalkembali;
    }

    public JTextField getTxtTanggalpinjam() {
        return txtTanggalpinjam;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtKodeanggota = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNamaanggota = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtKodebuku = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtJudulbuku = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTanggalpinjam = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTanggalkembali = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTerlambat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDenda = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTanggalDikembalikan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelPengembalian = new javax.swing.JTable();
        btnCancel = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Kode Anggota");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 100, 30);

        txtKodeanggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtKodeanggotaMouseEntered(evt);
            }
        });
        txtKodeanggota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKodeanggotaKeyPressed(evt);
            }
        });
        getContentPane().add(txtKodeanggota);
        txtKodeanggota.setBounds(140, 30, 540, 30);

        jLabel2.setText("Nama Anggota");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 100, 30);

        txtNamaanggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaanggotaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNamaanggota);
        txtNamaanggota.setBounds(140, 70, 540, 30);

        jLabel3.setText("Kode Buku");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 110, 100, 30);

        txtKodebuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKodebukuKeyPressed(evt);
            }
        });
        getContentPane().add(txtKodebuku);
        txtKodebuku.setBounds(140, 110, 540, 30);

        jLabel4.setText("Judul Buku");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 150, 100, 30);
        getContentPane().add(txtJudulbuku);
        txtJudulbuku.setBounds(140, 150, 540, 30);

        jLabel5.setText("Tanggal Pinjam");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 190, 100, 30);

        txtTanggalpinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalpinjamActionPerformed(evt);
            }
        });
        txtTanggalpinjam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTanggalpinjamKeyPressed(evt);
            }
        });
        getContentPane().add(txtTanggalpinjam);
        txtTanggalpinjam.setBounds(140, 190, 180, 30);

        jLabel6.setText("Tanggal Kembali");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 230, 100, 30);
        getContentPane().add(txtTanggalkembali);
        txtTanggalkembali.setBounds(140, 230, 180, 30);

        jLabel7.setText("Terlambat");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(370, 230, 100, 30);

        txtTerlambat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTerlambatActionPerformed(evt);
            }
        });
        getContentPane().add(txtTerlambat);
        txtTerlambat.setBounds(490, 230, 190, 30);

        jLabel8.setText("Denda");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(370, 270, 100, 30);
        getContentPane().add(txtDenda);
        txtDenda.setBounds(490, 270, 190, 30);

        jLabel9.setText("Tanggal Dikembalikan");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(18, 270, 102, 30);
        getContentPane().add(txtTanggalDikembalikan);
        txtTanggalDikembalikan.setBounds(140, 270, 180, 30);

        TabelPengembalian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Anggota", "Kode Buku", "Tanggal Pinjam", "Tanggal Dikembalikan", "Terlambat", "Denda"
            }
        ));
        jScrollPane1.setViewportView(TabelPengembalian);
        if (TabelPengembalian.getColumnModel().getColumnCount() > 0) {
            TabelPengembalian.getColumnModel().getColumn(0).setResizable(false);
            TabelPengembalian.getColumnModel().getColumn(1).setResizable(false);
            TabelPengembalian.getColumnModel().getColumn(2).setResizable(false);
            TabelPengembalian.getColumnModel().getColumn(3).setResizable(false);
            TabelPengembalian.getColumnModel().getColumn(4).setResizable(false);
            TabelPengembalian.getColumnModel().getColumn(5).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 380, 690, 280);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(430, 320, 110, 40);

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert);
        btnInsert.setBounds(20, 320, 90, 40);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate);
        btnUpdate.setBounds(150, 320, 100, 40);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(580, 320, 100, 40);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(290, 320, 100, 40);

        setSize(new java.awt.Dimension(724, 707));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaanggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaanggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaanggotaActionPerformed

    private void txtTerlambatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTerlambatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTerlambatActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        controller.insert();
        controller.clear();
        controller.viewTable();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        controller.update();
        controller.clear();
        controller.viewTable();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        controller.delete();
        controller.clear();
        controller.viewTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        controller.clear();
        controller.viewTable();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtKodeanggotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKodeanggotaMouseEntered
        // TODO add your handling code here
        
    }//GEN-LAST:event_txtKodeanggotaMouseEntered

    private void txtKodeanggotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodeanggotaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            controller.tampilNamaanggota();
        }
    }//GEN-LAST:event_txtKodeanggotaKeyPressed

    private void txtKodebukuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKodebukuKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            controller.tampilBuku();
        }
    }//GEN-LAST:event_txtKodebukuKeyPressed

    private void txtTanggalpinjamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTanggalpinjamKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            controller.tampilTanggal();
            controller.tanggal();
            controller.terlambat();
            controller.denda();
            
        }
    }//GEN-LAST:event_txtTanggalpinjamKeyPressed

    private void txtTanggalpinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalpinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalpinjamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelPengembalian;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDenda;
    private javax.swing.JTextField txtJudulbuku;
    private javax.swing.JTextField txtKodeanggota;
    private javax.swing.JTextField txtKodebuku;
    private javax.swing.JTextField txtNamaanggota;
    private javax.swing.JTextField txtTanggalDikembalikan;
    private javax.swing.JTextField txtTanggalkembali;
    private javax.swing.JTextField txtTanggalpinjam;
    private javax.swing.JTextField txtTerlambat;
    // End of variables declaration//GEN-END:variables
}
