/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dhea.view;

/**
 *
 * @author LABMM07
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItemAnggota = new javax.swing.JMenuItem();
        MenuItemBuku = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        MenuItemPeminjaman = new javax.swing.JMenuItem();
        MenuItemPengembalian = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MenuItemLapAnggota = new javax.swing.JMenuItem();
        MenuItemLapBuku = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MenuItemPeminjamanPerAnggota = new javax.swing.JMenuItem();
        MenuItemPeminjamanPerBulan = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        MenuItemPengembalianPerAnggota = new javax.swing.JMenuItem();
        MenuItemPengembalianPerBulan = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );

        getContentPane().add(DesktopPane, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        MenuItemAnggota.setText("Anggota");
        MenuItemAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAnggotaActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemAnggota);

        MenuItemBuku.setText("Buku");
        MenuItemBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemBukuActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItemBuku);

        jMenuItem1.setText("Contoh Internal");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Transaksi");

        MenuItemPeminjaman.setText("Peminjaman");
        jMenu3.add(MenuItemPeminjaman);

        MenuItemPengembalian.setText("Pengembalian");
        jMenu3.add(MenuItemPengembalian);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Laporan");

        MenuItemLapAnggota.setText("Anggota");
        jMenu4.add(MenuItemLapAnggota);

        MenuItemLapBuku.setText("Buku");
        jMenu4.add(MenuItemLapBuku);

        jMenu5.setText("Peminjaman");

        MenuItemPeminjamanPerAnggota.setText("Per Anggota");
        jMenu5.add(MenuItemPeminjamanPerAnggota);

        MenuItemPeminjamanPerBulan.setText("Per Bulan");
        MenuItemPeminjamanPerBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemPeminjamanPerBulanActionPerformed(evt);
            }
        });
        jMenu5.add(MenuItemPeminjamanPerBulan);

        jMenu4.add(jMenu5);

        jMenu6.setText("Pengembalian");

        MenuItemPengembalianPerAnggota.setText("Per Anggota");
        jMenu6.add(MenuItemPengembalianPerAnggota);

        MenuItemPengembalianPerBulan.setText("Per Bulan");
        jMenu6.add(MenuItemPengembalianPerBulan);

        jMenu4.add(jMenu6);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Exit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemPeminjamanPerBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemPeminjamanPerBulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuItemPeminjamanPerBulanActionPerformed

    private void MenuItemAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAnggotaActionPerformed
        // TODO add your handling code here:
        FormAnggota f = new FormAnggota();
        f.setVisible(true);
        f.toFront();
    }//GEN-LAST:event_MenuItemAnggotaActionPerformed

    private void MenuItemBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemBukuActionPerformed
        // TODO add your handling code here:
        FormBuku f = new FormBuku();
        f.setVisible(true);
        f.toFront();
    }//GEN-LAST:event_MenuItemBukuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        FormContoh f = new FormContoh();
        f.setVisible(true);
        f.toFront();
        DesktopPane.add(f);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenuItem MenuItemAnggota;
    private javax.swing.JMenuItem MenuItemBuku;
    private javax.swing.JMenuItem MenuItemLapAnggota;
    private javax.swing.JMenuItem MenuItemLapBuku;
    private javax.swing.JMenuItem MenuItemPeminjaman;
    private javax.swing.JMenuItem MenuItemPeminjamanPerAnggota;
    private javax.swing.JMenuItem MenuItemPeminjamanPerBulan;
    private javax.swing.JMenuItem MenuItemPengembalian;
    private javax.swing.JMenuItem MenuItemPengembalianPerAnggota;
    private javax.swing.JMenuItem MenuItemPengembalianPerBulan;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
